### PR TITLE
instance TrieKey (Natural, Word)

### PR DESCRIPTION
**Pull request by strake**

### CODE REVIEW

**Comment by glguy** [comment]
Would it be possible to have this not show a negative number?

```haskell
*Data.GenericTrie> singleton (maxBound :: Word) 'a'
fromList [(-1,'a')]
```

**Comment by strake** [comment]
It would require a new `type TrieRep Word`.

I opened #17 for `Natural` only. It should be easy to define a newtype of `IntMap` with `Word` keys and a saner `Show` instance; would it belong in this package, or a new dependency, or should i open a PR on containers?

**Comment by strake** [comment]
@glguy I still need a `Word` instance. What option you prefer for where to define the `Word`-keyed map?

**Comment by glguy** [comment]
I closed the ticket via the commit that implemented that instance.

**Comment by strake** [comment]
Derp, thank you!

**Pull request closed without merging**
