### PR TITLE
relax upper bound on base

### PR DESCRIPTION
**Pull request by ocramz**
Addresses #19

### CODE REVIEW

**Comment by treeowl** [comment]
This PR should probably be updated to relax the bound further. @glguy, do you need someone else to take over this package?

**Comment by glguy** [comment]
> This PR should probably be updated to relax the bound further. @glguy, do you need someone else to take over this package?

I'd be happy to hand it over. It's been off my radar for some time. Are you interested?

**Comment by ocramz** [comment]
I'd be happy to help out too. It's the fastest trie library I've
benchmarked and would be a pity to let it bitrot

**Comment by treeowl** [comment]
I'd be interested in co-maintaining it.

**Comment by glguy** [comment]
> I'd be interested in co-maintaining it.

OK, I've added you on hackage and this repository. Welcome!

**Comment by treeowl** [comment]
Thanks!

**Comment by ocramz** [comment]
@glguy could you add me as a maintainer as well please?

**Comment by treeowl** [comment]
Relaxing upper bounds should ideally include some changes around `StarIsType`. Probably just a few minutes. And someone needs to set up CI. There are no tests yet, but even making sure it compiles on everything it should would be nice.

**Comment by treeowl** [comment]
I bumped everything in #25, and cleaned up some build failures and so on in #27.

**Pull request closed without merging**
